{% set name = "cpp-opentelemetry-api" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/open-telemetry/opentelemetry-cpp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1fc371be049b3220b8b9571c8b713f03e9a84f3c5684363f64ccc814638391a5

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.1
    - ninja

test:
  commands:
    - test -d $PREFIX/include/opentelemetry/  # [unix]
    - if not exist %LIBRARY_INC%\opentelemetry exit 1  # [win]

about:
  home: https://github.com/open-telemetry/opentelemetry-cpp
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: The OpenTelemetry C++ Client
  description: |
    OpenTelemetry is a collection of tools, APIs, and SDKs. Use it to
    instrument, generate, collect, and export telemetry data (metrics,
    logs, and traces) to help you analyze your software’s performance
    and behavior.
  doc_url: https://opentelemetry.io/docs/instrumentation/cpp/
  dev_url: https://github.com/open-telemetry/opentelemetry-cpp

extra:
  recipe-maintainers:
    - lidavidm
